### ISSUE TITLE
Add button "Context menu" to main screen

### ISSUE THREAD

**Issue by ilya-corp** [SergeiMinaev/RMaps.0.9.x#5]
Not all prones have hardware button "Context menu". For example, my Highscreen Boost 3 SE Pro under Android 6.0 have not this button and I need to use third-party emulator for sole this sheet. It's take additional energy from my batterry.

Requirement:
Add button "Context menu" to main screen.
It should be small image, like button "Where me?".
Short press on this buttom should do the same, like when you press "Context menu" hardware button.

**Comment by SergeiMinaev** [comment]
Done :)
